stages:
  - build
  - eslint
  - prettier

build_webapp:
  stage: build
  image: node:latest
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - echo "Building site with Firestore credentials"
    - export FIREBASE_API_KEY=$FIREBASE_API_KEY
    - export FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN
    - export FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
    - npm run build

lint_prettier:
  stage: prettier
  image: node:latest
  script:
    - npm ci
    - npm run prettier-check

lint_eslint:
  stage: eslint
  image: node:latest
  script:
    - npm ci
    - npm run lint
